### ISSUE TITLE
Does not work with tonic feature "tls-roots"

### ISSUE THREAD

**Issue by shelbyd** [standard-ai/ya-gcp#35]
I get the following error when enabling the "tls-roots" feature of `tonic`. Specifically when running the bigtable example.

```
Error: BuildError(tonic::transport::Error(Transport, hyper::Error(Connect, Custom { kind: InvalidData, error: InvalidMessage(InvalidContentType) })))
```

My guess is some kind of handshake issue with TLS. It's entirely possible that this is an issue with some dependency, but I can only really tell the issue from my interaction with this crate.

**Comment by rnarubin** [comment]
Can you try using the `tls-webpki-roots` feature on tonic? it's possible our deps aren't specific enough with the features

**Comment by shelbyd** [comment]
Still fails the same way with `tls-webpki-roots`.
