### ISSUE TITLE
Many generated structs are not constructible

### ISSUE THREAD

**Issue by jneem** [standard-ai/ya-gcp#42]
At some point, the generated structs (such as `TimestampRange`) got `#[non_exhaustive]` annotations. But since we don't provide any constructors for them, they're now impossible to construct in downstream crates.

I think the `#[non_exhaustive]` annotations should be removed, at the cost of having breaking changes whenever they add new fields.

**Comment by rnarubin** [comment]
Generated structs should all impl Default for construction. It's not _great_ economics, but something like this should work: 

```
let range = {
  let mut r = TimestampRange::default();
  r.start_timestamp_micros = 5;
  r
};
```

The premise behind #[non_exhaustive] is to allow additions of public fields without a major version bump. We could do some more code gen to provide builders or constructors though

**Comment by jneem** [comment]
Ah, I'd totally missed the `Default` impls, sorry. I'm not sure more code gen is necessary -- downstream crates can make their own constructors to avoid repeating the awkwardness.
